import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { addDays, formatDateOnly, parseDateOnly } from '../common/json.js';
import {
  HIJRI_MONTH_NAMES,
  hijriDaysInMonth,
  hijriFromGregorian,
  hijriToGregorian,
  isHijriLeapYear,
  utcDateOnly,
  type HijriDate,
} from './hijri-calendar.js';

/**
 * Fixture generated by System.Globalization.HijriCalendar (HijriAdjustment = 0) via the
 * console program kept in __fixtures__/hijri.generator.cs.txt.
 */
interface ToDateTimeEdgeCase {
  year: number;
  month: number;
  day: number;
  result: string | null;
  error: string | null;
}

interface FromGregorianEdgeCase {
  date: string;
  result: string | null;
  error: string | null;
}

interface HijriFixture {
  hijriAdjustment: number;
  minSupportedDate: string;
  maxSupportedDate: string;
  monthNames: string[];
  gregorianToHijri: {
    rangeStart: string;
    rangeEnd: string;
    totalDays: number;
    yearDigests: Record<string, { days: number; sha256: string }>;
    monthStarts: Record<string, string>;
    days: Record<string, string>;
  };
  hijriToGregorian: {
    yearStart: number;
    yearEnd: number;
    firstOfMonth: Record<string, string>;
  };
  daysInMonth: Record<string, number[]>;
  leapYears: Record<string, boolean>;
  toDateTimeEdgeCases: ToDateTimeEdgeCase[];
  fromGregorianEdgeCases: FromGregorianEdgeCase[];
}

const fixture = JSON.parse(
  readFileSync(new URL('./__fixtures__/hijri.json', import.meta.url), 'utf8'),
) as HijriFixture;

const ymd = (hijri: HijriDate): string =>
  `${hijri.year}-${hijri.month}-${hijri.day}`;
/** Unpadded "y-m-d", the generator's format for dates outside 1000..9999. */
const gregorianYmd = (date: Date): string =>
  `${date.getUTCFullYear()}-${date.getUTCMonth() + 1}-${date.getUTCDate()}`;
const parseYmd = (value: string): Date => {
  const [year, month, day] = value.split('-').map(Number);
  return utcDateOnly(year, month, day);
};
const isoDate = (value: string): Date => {
  const date = parseDateOnly(value);
  if (!date) throw new Error(`Invalid fixture date ${value}`);
  return date;
};

const rangeStart = isoDate(fixture.gregorianToHijri.rangeStart);
const rangeEnd = isoDate(fixture.gregorianToHijri.rangeEnd);

function* fixtureRange(): Generator<Date> {
  for (
    let date = rangeStart;
    date.getTime() <= rangeEnd.getTime();
    date = addDays(date, 1)
  )
    yield date;
}

function nextHijriDay(hijri: HijriDate): HijriDate {
  if (hijri.day < hijriDaysInMonth(hijri.year, hijri.month))
    return { ...hijri, day: hijri.day + 1 };
  if (hijri.month === 12) return { year: hijri.year + 1, month: 1, day: 1 };
  return { year: hijri.year, month: hijri.month + 1, day: 1 };
}

describe('hijri-calendar (System.Globalization.HijriCalendar port)', () => {
  it('uses a fixture generated with HijriAdjustment = 0', () => {
    expect(fixture.hijriAdjustment).toBe(0);
    expect(fixture.gregorianToHijri.totalDays).toBe(6241);
  });

  it('exposes the month names used by the API', () => {
    expect([...HIJRI_MONTH_NAMES]).toEqual(fixture.monthNames);
  });

  it('matches GetYear/GetMonth/GetDayOfMonth on every Gregorian month start from 2019-12 to 2036-12', () => {
    const entries = Object.entries(fixture.gregorianToHijri.monthStarts);
    expect(entries).toHaveLength(205);
    for (const [iso, expected] of entries) {
      expect(ymd(hijriFromGregorian(isoDate(iso))), iso).toBe(expected);
    }
  });

  it('matches GetYear/GetMonth/GetDayOfMonth on every day of 2025-2027', () => {
    const entries = Object.entries(fixture.gregorianToHijri.days);
    expect(entries).toHaveLength(1095);
    for (const [iso, expected] of entries) {
      expect(ymd(hijriFromGregorian(isoDate(iso))), iso).toBe(expected);
    }
  });

  it('reproduces the per-year SHA-256 digests of every day from 2019-12-01 to 2036-12-31', () => {
    const lines = new Map<string, string[]>();
    let total = 0;
    for (const date of fixtureRange()) {
      const year = String(date.getUTCFullYear());
      const bucket = lines.get(year) ?? [];
      bucket.push(`${formatDateOnly(date)}=${ymd(hijriFromGregorian(date))}`);
      lines.set(year, bucket);
      total++;
    }
    expect(total).toBe(fixture.gregorianToHijri.totalDays);
    expect([...lines.keys()]).toEqual(
      Object.keys(fixture.gregorianToHijri.yearDigests),
    );
    for (const [year, digest] of Object.entries(
      fixture.gregorianToHijri.yearDigests,
    )) {
      const bucket = lines.get(year) ?? [];
      expect(bucket, year).toHaveLength(digest.days);
      expect(
        createHash('sha256').update(bucket.join('\n'), 'utf8').digest('hex'),
        year,
      ).toBe(digest.sha256);
    }
  });

  it('matches ToDateTime(y, m, 1) for every month of 1440-1460', () => {
    const entries = Object.entries(fixture.hijriToGregorian.firstOfMonth);
    expect(entries).toHaveLength(252);
    for (const [key, expected] of entries) {
      const [year, month] = key.split('-').map(Number);
      expect(formatDateOnly(hijriToGregorian(year, month, 1)), key).toBe(
        expected,
      );
    }
  });

  it('matches GetDaysInMonth and IsLeapYear for 1440-1460', () => {
    const years = Object.keys(fixture.daysInMonth);
    expect(years).toHaveLength(21);
    for (const year of years) {
      const months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
      expect(
        months.map((month) => hijriDaysInMonth(Number(year), month)),
        year,
      ).toEqual(fixture.daysInMonth[year]);
      expect(isHijriLeapYear(Number(year)), year).toBe(fixture.leapYears[year]);
    }
  });

  it('round-trips every day of the fixture range and advances one Hijri day at a time', () => {
    let previous: HijriDate | null = null;
    for (const date of fixtureRange()) {
      const hijri = hijriFromGregorian(date);
      const label = formatDateOnly(date);
      expect(
        hijriToGregorian(hijri.year, hijri.month, hijri.day).getTime(),
        label,
      ).toBe(date.getTime());
      if (previous) expect(ymd(hijri), label).toBe(ymd(nextHijriDay(previous)));
      previous = hijri;
    }
  });

  it('applies the ToDateTime range checks of .NET (ArgumentOutOfRangeException -> RangeError)', () => {
    expect(fixture.toDateTimeEdgeCases.length).toBeGreaterThanOrEqual(20);
    for (const edge of fixture.toDateTimeEdgeCases) {
      const label = `${edge.year}/${edge.month}/${edge.day}`;
      if (edge.result === null) {
        expect(edge.error, label).toBe('ArgumentOutOfRangeException');
        expect(
          () => hijriToGregorian(edge.year, edge.month, edge.day),
          label,
        ).toThrow(RangeError);
      } else {
        expect(
          gregorianYmd(hijriToGregorian(edge.year, edge.month, edge.day)),
          label,
        ).toBe(edge.result);
      }
    }
  });

  it('applies the GetDatePart range checks of .NET (ArgumentOutOfRangeException -> RangeError)', () => {
    for (const edge of fixture.fromGregorianEdgeCases) {
      if (edge.result === null) {
        expect(edge.error, edge.date).toBe('ArgumentOutOfRangeException');
        expect(
          () => hijriFromGregorian(parseYmd(edge.date)),
          edge.date,
        ).toThrow(RangeError);
      } else {
        expect(ymd(hijriFromGregorian(parseYmd(edge.date))), edge.date).toBe(
          edge.result,
        );
      }
    }
    expect(gregorianYmd(hijriToGregorian(1, 1, 1))).toBe(
      fixture.minSupportedDate,
    );
    expect(ymd(hijriFromGregorian(parseYmd(fixture.maxSupportedDate)))).toBe(
      '9666-4-3',
    );
  });

  it('rejects non-integer and NaN input', () => {
    expect(() => hijriToGregorian(1447, 9, 1.5)).toThrow(RangeError);
    expect(() => hijriToGregorian(Number.NaN, 9, 1)).toThrow(RangeError);
    expect(() => hijriDaysInMonth(1447, 2.5)).toThrow(RangeError);
    expect(() => isHijriLeapYear(0)).toThrow(RangeError);
    expect(() => hijriFromGregorian(new Date(Number.NaN))).toThrow(RangeError);
  });

  it('ignores the time of day and returns UTC-midnight dates (DateOnly semantics)', () => {
    const ramadanFirst = fixture.hijriToGregorian.firstOfMonth['1447-9'];
    expect(
      hijriFromGregorian(new Date(`${ramadanFirst}T23:59:59.999Z`)),
    ).toEqual({ year: 1447, month: 9, day: 1 });
    expect(hijriToGregorian(1447, 9, 1).toISOString()).toBe(
      `${ramadanFirst}T00:00:00.000Z`,
    );
  });

  it('builds exact UTC dates for years below 100', () => {
    expect(utcDateOnly(1, 1, 1).toISOString()).toBe('0001-01-01T00:00:00.000Z');
    expect(utcDateOnly(622, 7, 18).toISOString()).toBe(
      '0622-07-18T00:00:00.000Z',
    );
    expect(utcDateOnly(2026, 2, 17).getTime()).toBe(
      isoDate('2026-02-17').getTime(),
    );
  });
});
