import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { formatDateOnly, pad, parseDateOnly } from '../common/json.js';
import { utcDateOnly, type HijriDate } from './hijri-calendar.js';
import {
  buildHijriDisplay,
  generateHijriMonthMaps,
  hijriAnchorKey,
  ramadanDates,
  resolveHijriDate,
  type HijriDisplay,
  type HijriMonthAnchor,
} from './hijri.js';

/**
 * Fixture generated by verbatim C# replicas of HijriService.Generate,
 * QuestPdfGenerator.GetHijriDate and PublicController.BuildHijriDate
 * (__fixtures__/hijri.generator.cs.txt).
 */
interface DisplaySample {
  name: string;
  date: string;
  anchor: HijriMonthAnchor | null;
  display: HijriDisplay | null;
  resolved: { day: number; month: number; year: number } | null;
  resolveError: string | null;
}

interface HijriFixture {
  gregorianToHijri: {
    monthStarts: Record<string, string>;
    days: Record<string, string>;
  };
  monthMaps2026: HijriMonthAnchor[];
  shiftedAnchors2026: HijriMonthAnchor[];
  resolvedShifted2026: Record<string, string>;
  ramadan: {
    y2026: { dates: string[]; hijriYear: number; title: string };
    y2026Generated: string[];
    y2026Shifted: string[];
    y2027: string[];
    y2030: string[];
  };
  displaySamples: DisplaySample[];
}

const fixture = JSON.parse(
  readFileSync(new URL('./__fixtures__/hijri.json', import.meta.url), 'utf8'),
) as HijriFixture;

const ymd = (hijri: HijriDate): string =>
  `${hijri.year}-${hijri.month}-${hijri.day}`;
const isoDate = (value: string): Date => {
  const date = parseDateOnly(value);
  if (!date) throw new Error(`Invalid fixture date ${value}`);
  return date;
};
const anchorMap = (
  anchors: readonly HijriMonthAnchor[],
): Map<string, HijriMonthAnchor> =>
  new Map(
    anchors.map((anchor) => [
      hijriAnchorKey(anchor.year, anchor.month),
      anchor,
    ]),
  );
const anchorFor = (
  date: Date,
  anchors: ReadonlyMap<string, HijriMonthAnchor>,
): HijriMonthAnchor | null =>
  anchors.get(hijriAnchorKey(date.getUTCFullYear(), date.getUTCMonth() + 1)) ??
  null;
const invalidAnchor = (year: number, month: number): HijriMonthAnchor => ({
  year,
  month,
  hijriDayOnFirst: 31,
  hijriMonthOnFirst: 9,
  hijriYearOnFirst: 1447,
});

const expected2026 = fixture.monthMaps2026.map((map) => ({
  ...map,
  locked: false,
}));

describe('hijriAnchorKey', () => {
  it('is "year-month" without padding', () => {
    expect(hijriAnchorKey(2026, 3)).toBe('2026-3');
    expect(hijriAnchorKey(2026, 12)).toBe('2026-12');
  });
});

describe('generateHijriMonthMaps (HijriService.Generate)', () => {
  it('records the Hijri date of every Gregorian first-of-month of 2026', () => {
    expect(expected2026).toHaveLength(12);
    expect(
      generateHijriMonthMaps(isoDate('2026-01-01'), isoDate('2026-12-31')),
    ).toEqual(expected2026);
  });

  it('normalizes from and to to the first of their months', () => {
    expect(
      generateHijriMonthMaps(isoDate('2026-01-15'), isoDate('2026-12-03')),
    ).toEqual(expected2026);
    expect(
      generateHijriMonthMaps(isoDate('2026-03-31'), isoDate('2026-03-01')),
    ).toEqual([expected2026[2]]);
  });

  it('walks across year boundaries and agrees with .NET on every month start from 2019-12 to 2036-12', () => {
    const maps = generateHijriMonthMaps(
      isoDate('2019-12-25'),
      isoDate('2036-12-01'),
    );
    expect(maps).toHaveLength(205);
    for (const map of maps) {
      const key = `${map.year}-${pad(map.month)}-01`;
      expect(
        `${map.hijriYearOnFirst}-${map.hijriMonthOnFirst}-${map.hijriDayOnFirst}`,
        key,
      ).toBe(fixture.gregorianToHijri.monthStarts[key]);
      expect(map.locked).toBe(false);
    }
  });

  it('returns nothing when from is after to', () => {
    expect(
      generateHijriMonthMaps(isoDate('2026-02-01'), isoDate('2026-01-31')),
    ).toEqual([]);
  });
});

describe('resolveHijriDate (QuestPdfGenerator.GetHijriDate)', () => {
  it('uses the tabular calendar without an anchor', () => {
    const entries = Object.entries(fixture.gregorianToHijri.days);
    expect(entries).toHaveLength(1095);
    for (const [iso, expected] of entries) {
      expect(ymd(resolveHijriDate(isoDate(iso), null)), iso).toBe(expected);
    }
  });

  it('shifts every day of 2026 through the anchor of its month', () => {
    const anchors = anchorMap(fixture.shiftedAnchors2026);
    const entries = Object.entries(fixture.resolvedShifted2026);
    expect(entries).toHaveLength(365);
    for (const [iso, expected] of entries) {
      const date = isoDate(iso);
      expect(ymd(resolveHijriDate(date, anchorFor(date, anchors))), iso).toBe(
        expected,
      );
    }
  });

  it('matches .NET for the sampled anchors, including ignored (month <= 0 or year <= 1) and invalid ones', () => {
    let checked = 0;
    for (const sample of fixture.displaySamples) {
      const date = isoDate(sample.date);
      // GetHijriDate looks the anchor up by the date's month; a sample whose anchor belongs to another month is covered below.
      if (
        sample.anchor &&
        (sample.anchor.year !== date.getUTCFullYear() ||
          sample.anchor.month !== date.getUTCMonth() + 1)
      )
        continue;
      checked++;
      if (sample.resolveError !== null) {
        expect(sample.resolveError, sample.name).toBe(
          'ArgumentOutOfRangeException',
        );
        expect(
          () => resolveHijriDate(date, sample.anchor),
          sample.name,
        ).toThrow(RangeError);
      } else {
        expect(resolveHijriDate(date, sample.anchor), sample.name).toEqual(
          sample.resolved,
        );
      }
    }
    expect(checked).toBeGreaterThanOrEqual(28);
  });

  it('applies whichever anchor it is handed; the caller is responsible for the month lookup', () => {
    const sample = fixture.displaySamples.find((candidate) =>
      candidate.name.startsWith('anchor for another month'),
    );
    if (!sample?.anchor || !sample.display)
      throw new Error('Fixture sample missing');
    const date = isoDate(sample.date);
    const { year, month, day } = sample.display;
    expect(resolveHijriDate(date, sample.anchor)).toEqual({ year, month, day });
    expect(
      resolveHijriDate(date, anchorFor(date, anchorMap([sample.anchor]))),
    ).toEqual(sample.resolved);
  });
});

describe('buildHijriDisplay (PublicController.BuildHijriDate)', () => {
  it('matches .NET for every sample and returns null for invalid anchors', () => {
    expect(fixture.displaySamples.length).toBeGreaterThanOrEqual(30);
    expect(
      fixture.displaySamples.filter((sample) => sample.display === null).length,
    ).toBeGreaterThanOrEqual(9);
    for (const sample of fixture.displaySamples) {
      expect(
        buildHijriDisplay(isoDate(sample.date), sample.anchor),
        sample.name,
      ).toEqual(sample.display);
    }
  });

  it('serializes the fields in the .NET order', () => {
    const display = buildHijriDisplay(isoDate('2026-02-18'), null);
    expect(Object.keys(display ?? {})).toEqual([
      'day',
      'month',
      'year',
      'monthName',
      'formatted',
    ]);
    expect(display?.formatted).toBe('Ramadan 2, 1447');
  });

  it('returns null for dates before the calendar epoch', () => {
    expect(buildHijriDisplay(utcDateOnly(622, 7, 17), null)).toBeNull();
    expect(buildHijriDisplay(utcDateOnly(622, 7, 18), null)).toEqual({
      day: 1,
      month: 1,
      year: 1,
      monthName: 'Muharram',
      formatted: 'Muharram 1, 1',
    });
  });

  it('ignores the anchor only when its Hijri month or year is unset', () => {
    const date = isoDate('2026-09-10');
    const plain = buildHijriDisplay(date, null);
    expect(
      buildHijriDisplay(date, {
        year: 2026,
        month: 9,
        hijriDayOnFirst: 99,
        hijriMonthOnFirst: 0,
        hijriYearOnFirst: 1448,
      }),
    ).toEqual(plain);
    expect(
      buildHijriDisplay(date, {
        year: 2026,
        month: 9,
        hijriDayOnFirst: 99,
        hijriMonthOnFirst: 13,
        hijriYearOnFirst: 1,
      }),
    ).toEqual(plain);
    expect(
      buildHijriDisplay(date, {
        year: 2026,
        month: 9,
        hijriDayOnFirst: 99,
        hijriMonthOnFirst: 3,
        hijriYearOnFirst: 1448,
      }),
    ).toBeNull();
  });
});

describe('ramadanDates (GenerateRamadanPdfAsync)', () => {
  it('finds Ramadan 1447 in 2026 without anchors', () => {
    const dates = ramadanDates(2026, new Map());
    expect(dates.map((date) => formatDateOnly(date))).toEqual(
      fixture.ramadan.y2026.dates,
    );
    expect(dates).toHaveLength(30);
    const hijriYear = resolveHijriDate(dates[0], null).year;
    expect(hijriYear).toBe(fixture.ramadan.y2026.hijriYear);
    expect(`Ramadan ${hijriYear} / 2026`).toBe(fixture.ramadan.y2026.title);
  });

  it('is unchanged by generated (tabular) anchors', () => {
    const anchors = anchorMap(
      generateHijriMonthMaps(isoDate('2026-01-01'), isoDate('2026-12-31')),
    );
    expect(
      ramadanDates(2026, anchors).map((date) => formatDateOnly(date)),
    ).toEqual(fixture.ramadan.y2026Generated);
  });

  it('moves with moon-sighting anchors', () => {
    const dates = ramadanDates(2026, anchorMap(fixture.shiftedAnchors2026)).map(
      (date) => formatDateOnly(date),
    );
    expect(dates).toEqual(fixture.ramadan.y2026Shifted);
    expect(dates[0]).toBe('2026-02-16');
  });

  it('handles other years, including a Gregorian year with two Ramadans', () => {
    expect(
      ramadanDates(2027, new Map()).map((date) => formatDateOnly(date)),
    ).toEqual(fixture.ramadan.y2027);
    const y2030 = ramadanDates(2030, new Map()).map((date) =>
      formatDateOnly(date),
    );
    expect(y2030).toEqual(fixture.ramadan.y2030);
    expect(y2030.length).toBeGreaterThan(30);
    expect(y2030[0]).toBe('2030-01-05');
    expect(y2030[y2030.length - 1]).toBe('2030-12-31');
  });

  it('only consults anchors of the requested year and propagates invalid anchors like .NET', () => {
    const otherYear = new Map([
      [hijriAnchorKey(2025, 2), invalidAnchor(2025, 2)],
    ]);
    expect(
      ramadanDates(2026, otherYear).map((date) => formatDateOnly(date)),
    ).toEqual(fixture.ramadan.y2026.dates);
    const invalid = new Map([
      [hijriAnchorKey(2026, 2), invalidAnchor(2026, 2)],
    ]);
    expect(() => ramadanDates(2026, invalid)).toThrow(RangeError);
  });
});
